
CREATE TABLE IF NOT EXISTS CLIENTE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    genero VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENDERECO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cep VARCHAR(255) NOT NULL,
    uf VARCHAR(10) NOT NULL,
    gia INT NOT NULL,
	logradouro VARCHAR(255) NOT NULL,
	complemento VARCHAR(255) NOT NULL,
	bairro VARCHAR(255) NOT NULL,
	localidade VARCHAR(255) NOT NULL,
    ibge VARCHAR(255) NOT NULL,
	ddd VARCHAR(255) NOT NULL,
	siafi VARCHAR(255) NOT NULL,
    clienteId INT NOT NULL,
	foreign key(clienteId) references CLIENTE(id)
);